"""add_default_password_and_is_password_reset_fields

Revision ID: 21e62823406e
Revises: c18526c4b3a7
Create Date: 2025-01-29 17:20:16.151246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e62823406e'
down_revision: Union[str, None] = 'c18526c4b3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_password', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('is_password_reset', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('verification_token', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_password_reset')
    op.drop_column('users', 'default_password')
    # ### end Alembic commands ###
